#连接池的配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
                        classpath:/static/,classpath:/public/,file:E:\projectDATA\img\

#更改端口
server:
  port: 8081

#mybatis的配置
mybatis:
  mapper-locations: classpath*:com/example/jdbc/mapper/*.xml
  type-aliases-package: com.example.jdbc.pojo


